package com.example.ecommercebackend.service.impl;

import com.example.ecommercebackend.service.QueryExecutionService;
import com.example.ecommercebackend.exception.BadRequestException;
import net.sf.jsqlparser.JSQLParserException;
import net.sf.jsqlparser.parser.CCJSqlParserUtil;
import net.sf.jsqlparser.statement.Statement;
import net.sf.jsqlparser.statement.select.Limit;
import net.sf.jsqlparser.statement.select.PlainSelect;
import net.sf.jsqlparser.statement.select.Select;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import net.sf.jsqlparser.util.TablesNamesFinder;

import java.util.List;
import java.util.Map;

/**
 * Service implementation for safely executing raw SQL queries generated by the AI Chatbot.
 * Uses JSqlParser to parse the SQL into an Abstract Syntax Tree (AST), validates it,
 * and automatically injects a LIMIT clause to prevent Out-Of-Memory (OOM) errors.
 */
@Service
public class QueryExecutionServiceImpl implements QueryExecutionService {

    private final JdbcTemplate jdbcTemplate;

    public QueryExecutionServiceImpl(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /**
     * Executes a read-only SELECT query safely.
     *
     * @param sql The raw SQL string generated by the AI
     * @return List of rows represented as key-value maps
     * @throws BadRequestException if the SQL is invalid or not a SELECT query
     */
    @Override
    @Transactional(readOnly = true)
    public List<Map<String, Object>> executeReadOnlyQuery(String sql, Long currentUserId, String currentUserRole) {
        if (sql == null || sql.trim().isEmpty()) {
            throw new BadRequestException("SQL query cannot be empty or null.");
        }

        try {
            // 1. AST Parsing with JSqlParser
            Statement statement = CCJSqlParserUtil.parse(sql);

            // 2. Ensure it is a SELECT statement (blocks DROP, DELETE, etc.)
            if (!(statement instanceof Select)) {
                throw new BadRequestException("Security Violation: Only SELECT queries are allowed to be executed.");
            }

            Select selectStatement = (Select) statement;

            // --- TASK 2: Implement AST Table Extraction & System Table Deny-List ---
            TablesNamesFinder tablesNamesFinder = new TablesNamesFinder();
            List<String> tableList = tablesNamesFinder.getTableList(selectStatement);
            List<String> systemTables = List.of("users", "refresh_tokens", "audit_logs", "customer_profiles", "carts");
            
            for (String table : tableList) {
                if (systemTables.contains(table.toLowerCase())) {
                    throw new BadRequestException("Security Violation: Access to system tables via AI is strictly prohibited.");
                }
            }

            // --- TASK 3 & 4: Enforce Tenant Isolation ---
            String sqlUpper = sql.toUpperCase().replaceAll("\\s+", " ");
            
            // Task 3: INDIVIDUAL Users
            if ("INDIVIDUAL".equalsIgnoreCase(currentUserRole)) {
                List<String> restrictedTables = List.of("orders", "reviews", "order_items", "shipments");
                boolean accessesRestrictedTable = tableList.stream().anyMatch(t -> restrictedTables.contains(t.toLowerCase()));
                
                if (accessesRestrictedTable) {
                    // Check for USER_ID = {id} with flexibility for spaces and aliases (e.g. O.USER_ID=5 or USER_ID = 5)
                    String pattern1 = "USER_ID=" + currentUserId;
                    String pattern2 = "USER_ID = " + currentUserId;
                    String pattern3 = "USER_ID= " + currentUserId;
                    String pattern4 = "USER_ID =" + currentUserId;

                    if (!(sqlUpper.contains(pattern1) || sqlUpper.contains(pattern2) || 
                          sqlUpper.contains(pattern3) || sqlUpper.contains(pattern4))) {
                        throw new BadRequestException("Security Violation: You can only query your own data. Strict tenant filter 'USER_ID = " + currentUserId + "' is missing for restricted tables: " + tableList);
                    }
                    if (sqlUpper.contains(" OR ")) {
                        throw new BadRequestException("Security Violation: 'OR' bypass detected. Use 'AND' or 'IN' for multiple conditions.");
                    }
                }
            }
            
            // Task 4: CORPORATE Users
            if ("CORPORATE".equalsIgnoreCase(currentUserRole)) {
                List<String> restrictedTables = List.of("orders", "products", "reviews", "stores");
                boolean accessesRestrictedTable = tableList.stream().anyMatch(t -> restrictedTables.contains(t.toLowerCase()));
                
                if (accessesRestrictedTable) {
                    // Check for CORPORATE_USER_ID = {id} with flexibility
                    String pattern1 = "CORPORATE_USER_ID=" + currentUserId;
                    String pattern2 = "CORPORATE_USER_ID = " + currentUserId;
                    String pattern3 = "CORPORATE_USER_ID= " + currentUserId;
                    String pattern4 = "CORPORATE_USER_ID =" + currentUserId;

                    if (!(sqlUpper.contains(pattern1) || sqlUpper.contains(pattern2) || 
                          sqlUpper.contains(pattern3) || sqlUpper.contains(pattern4))) {
                        throw new BadRequestException("Security Violation: Corporate isolation failed. Missing 'CORPORATE_USER_ID = " + currentUserId + "' filter for tables: " + tableList);
                    }
                    if (sqlUpper.contains(" OR ")) {
                        throw new BadRequestException("Security Violation: 'OR' bypass detected. Corporate isolation requires strict AND filters.");
                    }
                }
            }

            // 3. Inject LIMIT 100 to prevent OOM
            if (selectStatement.getSelectBody() instanceof PlainSelect) {
                PlainSelect plainSelect = (PlainSelect) selectStatement.getSelectBody();
                if (plainSelect.getLimit() == null) {
                    Limit limit = new Limit();
                    limit.setRowCount(new net.sf.jsqlparser.expression.LongValue(100));
                    plainSelect.setLimit(limit);
                }
            }

            // Get the safe and limited SQL
            String safeSql = selectStatement.toString();

            // 4. Execute via JdbcTemplate
            return jdbcTemplate.queryForList(safeSql);

        } catch (JSQLParserException e) {
            // If it fails to parse, block it (prevents jailbreaking or malformed SQL injection)
            throw new BadRequestException("Failed to parse SQL AST. Invalid syntax or unsupported query structure: " + e.getMessage());
        }
    }
}
