spring.application.name=ecommercebackend

# Varsayılan profil (postgres veya mysql olarak değiştirebilirsiniz)
spring.profiles.active=postgres

# JPA Ortak Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Disable Spring Security AuthenticationProvider warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# Disable SpringDoc default endpoint warnings
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
