spring.application.name=ecommercebackend

# Varsayılan profil (postgres veya mysql olarak değiştirebilirsiniz)
spring.profiles.active=postgres

# JPA Ortak Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Disable Spring Security AuthenticationProvider warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# Enable SpringDoc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
